### ISSUE TITLE
add maya's awesome logo

### ISSUE THREAD

**Issue by junosuarez** [codeforamerica/mobile-orchestra#3]
![mo-logo](https://cloud.githubusercontent.com/assets/1106489/2606616/bf0020be-bb52-11e3-913f-4ad7ede1b5ee.png)

**Comment by drewrwilson** [comment]
:bike: :performing_arts:

**Comment by junosuarez** [comment]
:cake: anyone want to take this issue?

**Comment by ainsleywagon** [comment]
I got this.

**Comment by junosuarez** [comment]
Cool, I assigned you to the task @ainsleywagon :)

**Comment by ainsleywagon** [comment]
Done.

**Comment by junosuarez** [comment]
Closed in 063272b301d6c6eb58d3178e23c6799d77f311b0

**Comment by maya** [comment]
Added in the logo as an svg :dolphin:
