### ISSUE TITLE
Move repository to codeforamerica account

### ISSUE THREAD

**Issue by maya** [codeforamerica/mobile-orchestra#4]
Mike asked that all our work be here.

**Comment by junosuarez** [comment]
I am an admin on the @codeforamerica org - @fureigh I can move the repo over if you make me the owner of this repo. I know there are several other fellows who are also admins and any of them can do it as well (no sure who all they are offhand)

**Comment by fureigh** [comment]
Thanks for the offer, @jden. Apparently I've been made an admin on the @codeforamerica org since last I tried. This repo's new home is https://github.com/codeforamerica/mobile-orchestra.

**Comment by fureigh** [comment]
(...but now I can't close this ticket. Womp womp.)

**Comment by maya** [comment]
thanks guys! closing now :+1:

**Comment by drewrwilson** [comment]
rad, do I need to update anything on my local git? Like do I need to reclone it? Or does it magically just do it? 

:sparkles:

**Comment by junosuarez** [comment]
@drewrwilson https://help.github.com/articles/changing-a-remote-s-url

**Comment by drewrwilson** [comment]
Thanks!
:dart: :thought_balloon: :camel:
